### ISSUE TITLE
method lines and words doesn't work.

### ISSUE THREAD

**Issue by FrankTrog** [chrisma/birdman.js#1]
I have been trying to use the method lines or words and it just doesn't do anything on the page, though it doesn't throw an error either. You might want to look into it. 

$('p').birdman({method: 'lines'});

**Comment by chrisma** [comment]
Hello Frank,

thanks for your report. The `lines` and `words` methods don't work without explicitly passing the `order` config parameter, as they don't have any default order set (in contrast to `letter`, where alphabetical order is default).
That is not adequately described in the README, i'll update that.

Here [https://jsfiddle.net/1bLo8bc0/](https://jsfiddle.net/1bLo8bc0/) is a working example with words and lines.
(The `<br/>` tags are stripped in the lines version, notice the CSS if you want to keep the line breaks.)

**Comment by FrankTrog** [comment]
Thanks for responding @chrisma, explaining the issue and providing a working example.
