### ISSUE TITLE
Cyrillic symbols support

### ISSUE THREAD

**Issue by Kristinita** [chrisma/birdman.js#4]
Hello. What I need to make that Cyrillic letters were correctly displayed? Latin letters are displayed correct, but Cyrillic it isn't visible.

Example — http://cssdeck.com/labs/ymuyvw2y

Thanks.

**Comment by chrisma** [comment]
Hi @Kristinita 
Thanks for your question.
There are only defaults for Latin letters at the moment, so for birdman.js to display different characters you need to set the `order` attribute of the configuration object, see the [README](https://github.com/chrisma/birdman.js#configuration). The order of the letters in the array decides the order in which the letters are shown.
See also your fixed example — http://cssdeck.com/labs/3jqnwd4i
